"""add_posts_table

Revision ID: 0ec773f22252
Revises: 8375d1acc8f0
Create Date: 2026-01-05 21:17:01.044081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec773f22252'
down_revision = '8375d1acc8f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    升级数据库结构（应用此迁移）
    这个函数会在执行 alembic upgrade 时被调用
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False, comment='Post 唯一标识'),
    sa.Column('trip_id', sa.UUID(), nullable=False, comment='关联的行程 ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='发布用户 ID（从 trips.user_id 获取）'),
    sa.Column('title', sa.Text(), nullable=False, comment='分享标题（默认：Trip · {n} stops，或根据主题生成）'),
    sa.Column('summary', sa.Text(), nullable=True, comment='行程摘要（从 stops 的 ai_summary / memories 拼接生成）'),
    sa.Column('cover_poi_id', sa.Text(), nullable=True, comment='封面 POI ID（默认取第一站 stop.poi_id）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_trip_id'), 'posts', ['trip_id'], unique=False)
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    降级数据库结构（回滚此迁移）
    这个函数会在执行 alembic downgrade 时被调用
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_trip_id'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
