"""update_posts_table_v2

Revision ID: 394c80133492
Revises: 0ec773f22252
Create Date: 2026-01-05 21:49:43.067708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '394c80133492'
down_revision = '0ec773f22252'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    升级数据库结构（应用此迁移）
    这个函数会在执行 alembic upgrade 时被调用
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('reflection', sa.Text(), nullable=True, comment='用户对行程的感想/反思（可选）'))
    op.add_column('posts', sa.Column('cover_image_url', sa.String(length=1000), nullable=True, comment='封面图片 URL（用户上传的图片，可选）'))
    # 先添加为 nullable=True，然后填充默认值，最后改为 nullable=False
    op.add_column('posts', sa.Column('manifest_json', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Trip 快照（stops: seq/poi_id/name/status/lat/lon/user_logs/ai_summary），发布时冻结'))
    
    # 为已有的 posts 填充默认的 manifest_json（如果存在旧数据）
    # 这里使用一个空的默认结构
    op.execute("""
        UPDATE posts 
        SET manifest_json = '{"trip_id": "", "status": "UNKNOWN", "total_stops": 0, "stops": []}'::jsonb
        WHERE manifest_json IS NULL
    """)
    
    # 现在将 manifest_json 改为 NOT NULL
    op.alter_column('posts', 'manifest_json', nullable=False)
    
    op.alter_column('posts', 'trip_id',
               existing_type=sa.UUID(),
               comment='关联的行程 ID（原始 trip）',
               existing_comment='关联的行程 ID',
               existing_nullable=False)
    op.alter_column('posts', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               comment='分享标题（用户可编辑，默认为空字符串）',
               existing_comment='分享标题（默认：Trip · {n} stops，或根据主题生成）',
               existing_nullable=False)
    op.alter_column('posts', 'cover_poi_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               comment='封面 POI ID（备选封面，如果没有上传图片则使用）',
               existing_comment='封面 POI ID（默认取第一站 stop.poi_id）',
               existing_nullable=True)
    op.create_index(op.f('ix_posts_cover_poi_id'), 'posts', ['cover_poi_id'], unique=False)
    op.drop_column('posts', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    降级数据库结构（回滚此迁移）
    这个函数会在执行 alembic downgrade 时被调用
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True, comment='行程摘要（从 stops 的 ai_summary / memories 拼接生成）'))
    op.drop_index(op.f('ix_posts_cover_poi_id'), table_name='posts')
    op.alter_column('posts', 'cover_poi_id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               comment='封面 POI ID（默认取第一站 stop.poi_id）',
               existing_comment='封面 POI ID（备选封面，如果没有上传图片则使用）',
               existing_nullable=True)
    op.alter_column('posts', 'title',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               comment='分享标题（默认：Trip · {n} stops，或根据主题生成）',
               existing_comment='分享标题（用户可编辑，默认为空字符串）',
               existing_nullable=False)
    op.alter_column('posts', 'trip_id',
               existing_type=sa.UUID(),
               comment='关联的行程 ID',
               existing_comment='关联的行程 ID（原始 trip）',
               existing_nullable=False)
    op.drop_column('posts', 'manifest_json')
    op.drop_column('posts', 'cover_image_url')
    op.drop_column('posts', 'reflection')
    # ### end Alembic commands ###
