"""add core tables

Revision ID: 453181091015
Revises: acd054805bbe
Create Date: 2026-01-03 18:38:38.815506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '453181091015'
down_revision = 'acd054805bbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    升级数据库结构（应用此迁移）
    这个函数会在执行 alembic upgrade 时被调用
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='用户唯一标识'),
    sa.Column('openid', sa.String(length=128), nullable=False, comment='微信 OpenID（唯一）'),
    sa.Column('nickname', sa.String(length=128), nullable=True, comment='用户昵称'),
    sa.Column('avatar', sa.String(length=512), nullable=True, comment='用户头像 URL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False, comment='行程唯一标识'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='所属用户 ID'),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='tripstatus', native_enum=False), nullable=False, comment='行程状态：DRAFT/ACTIVE/COMPLETED/ARCHIVED'),
    sa.Column('request_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='用户请求 JSON（如兴趣、时间预算等）'),
    sa.Column('run_id', sa.Text(), nullable=True, comment='LangGraph run_id（可用于调试追踪）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('trip_stops',
    sa.Column('id', sa.UUID(), nullable=False, comment='站点唯一标识'),
    sa.Column('trip_id', sa.UUID(), nullable=False, comment='所属行程 ID'),
    sa.Column('seq', sa.Integer(), nullable=False, comment='站点顺序（1-based，便于排序）'),
    sa.Column('poi_id', sa.Text(), nullable=False, comment='POI ID（来自 mock_db 或外部数据源）'),
    sa.Column('name', sa.Text(), nullable=False, comment='站点名称（如：故宫、颐和园）'),
    sa.Column('category', sa.Text(), nullable=True, comment='站点分类（如：历史、自然、美食）'),
    sa.Column('distance_m', sa.Integer(), nullable=True, comment='距离上一站的距离（米）'),
    sa.Column('status', sa.Enum('UPCOMING', 'ARRIVED', 'COMPLETED', 'SKIPPED', name='stopstatus', native_enum=False), nullable=False, comment='站点状态：UPCOMING/ARRIVED/COMPLETED/SKIPPED'),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True, comment='到达时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_stops_trip_id'), 'trip_stops', ['trip_id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False, comment='记忆唯一标识'),
    sa.Column('trip_id', sa.UUID(), nullable=False, comment='所属行程 ID'),
    sa.Column('stop_id', sa.UUID(), nullable=True, comment='关联站点 ID（可选）'),
    sa.Column('source', sa.Enum('USER', 'AI', name='memorysource', native_enum=False), nullable=False, comment='记忆来源：USER/AI'),
    sa.Column('type', sa.Enum('NOTE', 'INSIGHT', name='memorytype', native_enum=False), nullable=False, comment='记忆类型：NOTE/INSIGHT'),
    sa.Column('content', sa.Text(), nullable=False, comment='记忆内容（文本）'),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='元数据 JSON（如图片、标签、情感分析结果等）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['stop_id'], ['trip_stops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_stop_id'), 'memories', ['stop_id'], unique=False)
    op.create_index(op.f('ix_memories_trip_id'), 'memories', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    降级数据库结构（回滚此迁移）
    这个函数会在执行 alembic downgrade 时被调用
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memories_trip_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_stop_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_trip_stops_trip_id'), table_name='trip_stops')
    op.drop_table('trip_stops')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
